export const REDUX_TEST_REQUEST = 'REDUX_TEST_REQUEST';
export const REDUX_TEST_REQUEST_SUCCESS = 'REDUX_TEST_REQUEST_SUCCESS';
export const REDUX_TEST_REQUEST_FAILURE = 'REDUX_TEST_REQUEST_FAILURE';
